from enum import Enum


class InstrumentType(Enum):
    PS = "PS"
    DMM = "DMM"
    SCOPE = "SCOPE"
    DAQ = "DAQ"
    BERT = "BERT"
    SWITCH = "SWITCH"
    ELECTRONIC_LOAD = "ELECTRONIC_LOAD"
    POWER_METER = "POWER_METER"
    GENERATOR_SIGNAL = "GENERATOR_SIGNAL"
    GENERATOR_WAVEFORM = "GENERATOR_WAVEFORM"
    GENERATOR_NOISE = "GENERATOR_NOISE"
    GENERATOR_PATTERN = "GENERATOR_PATTERN"
    GENERATOR_PULSE = "GENERATOR_PULSE"
    FREQUENCY_COUNTER = "FREQUENCY_COUNTER"
    NETWORK_ANALYZER = "NETWORK_ANALYZER"
    THERMAL_HEAD = "THERMAL_HEAD"
